namespace: derekwaters
name: ansible_schema
version: 1.0.0
readme: README.md
authors:
- Derek Waters <derek@frisbeeworld.com>
description: A collection for asserting Ansible schema definitions
license:
- GPL-2.0-or-later
tags:
- vars
- schema
- assertion
dependencies: {}
repository: https://github.com/derekwaters/ansible_schema
documentation: https://github.com/derekwaters/ansible_schema
homepage: https://github.com/derekwaters/ansible_schema
issues: https://github.com/derekwaters/ansible_schema/issues

build_ignore:
  - 'examples/'
  - 'tests/'
  - '.gitignore'
  - '.git'
